### PR TITLE
Fix coverage, add cross platform configuration

### PR DESCRIPTION
**Pull request by Miladiir**
Line 21 of package.json fixes the issue https://github.com/welkie/node-boilerplate/issues/45.

I took the opportunity to tune the configuration a bit, so that it works on all node supported platforms.
Using `rm -r dist 2> /dev/null; node_modules/.bin/tsc` is problematic for a number of reasons:

1. `rm -r dist; tsc` does not work on Windows.
2. If the removal fails, the user does not get informed why.
3. There is no /dev/null on all platforms. Maybe this works in Windows in Cygwin/Git Bash etc.
4. The script executed by `npm run` has `node_modules/.bin/` in its path.

To make the boilerplate usable on all platforms I recommend to use this line as provided. The only change you should make is the package that is used to remove the folder `dist`. Under no circumstance should errors be suppressed or hidden.

Additionally `npm run build && nyc --reporter=text --reporter=lcov mocha 'dist/test/**/*.test.js'` is problematic:

1. It is unnecessary to call mocha with `'dist/test/**/*.test.js` . `mocha dist/test` is enough.
2. Specifying the path as above does not work on all platforms.

I therefore suggest to change the mocha call as in (1) to make it work on all platforms. In case you don't want to merge the config as is, the line should be changed to `npm run build && nyc --reporter=text --reporter=lcov mocha dist/test`

In this pull request I also changed the call to only `nyc mocha` and moved the configuration of the two packages into their own places. This has the advantage of cleaning up the run script while having the disadvantage of making it less clear with what parameters the packages are executed. To a beginner it might not be obvious what the "mocha" and "nyc" portions of the package.json do. On the other hand, the original script is pretty verbose and requires knowledge of nyc reporters etc.
That change is therefore not required. I just think its nicer this way.

### CODE REVIEW

**Comment by Miladiir** [comment]
I found out why there was no coverage when using the latest version of nyc. The option `--exclude-after-remap` is the culprit. Running `nyc mocha` with nyc@14 yields no coverage, while `nyc --exclude-after-remap false mocha` gets the usual result.
I add the option `extension` to the nyc configuration to mitigate this problem. Alternatively the problem can be resolved by using the switch `--exclude-after-remap false` on nyc, or adding `"exclude-after-remap": false" to the configuration.

Usually also the files that are checked for coverage are supplied using include and exclude statements, e.g.
```
"nyc": {
    "reporter": [
      "text",
      "lcov"
    ],
    "extension": [
    	".ts"
    ],
    "include": [
        "src"
    ]
  }
```
However, nyc is behaving weird again. I have to supply both src and dist/src as filepaths to make it work. This release seems to just be broken. Probably because most just use ts-node and everything just works (tm) albeit slowly, because ts-node is broken aswell.

**Comment by welkie** [comment]
@Miladiir  First off, thanks for the PR. I didn't realize anyone found this example I hosted notable. We ended up using this in production until we migrated from Node.js to Go (our use case worked well with Go). I still like to use Node.js and TypeScript for non-CPU intensive stuff though, so I'm still interested in solving this problem. The state of affairs with nyc and ts-node was rocky when I made this. It sucks to hear things haven't gotten better.

I agree with the cross-platform changes and general cleanup of this PR. I'd like to test the coverage myself locally before merging it though. Will review soon

**Comment by welkie** [comment]
@Miladiir As an additional comment, regarding what you said earlier:

> Probably because most just use ts-node and everything just works (tm) albeit slowly, because ts-node is broken aswell.

If you're curious, my original reason for creating this boilerplate and explicitly not using ts-node was because I found the code coverage reports innacurate when I used ts-node. I would run `npm test` and get 75% coverage (with a bunch of red lines in the HTML report) and then run `npm test` again and get 95% (at which point my CircleCI passed). I ended up manually rerunning CircleCI and found that unacceptable. I found that running nyc against JS files instead of using ts-node yielded consistent coverage reports.

I have no idea if the problem was ts-node itself, or an issue with nyc, or an issue with how I had it all wired together. If you have any ideas, let me know.

**Comment by Miladiir** [comment]
I am not 100 % sure, but here is what I remember from the top of my head. I think ts-node cached its results previously. They disabled caching in some recent version to combat problems like yours. The problem now is that without caching, startup is incredibly slow on codebases that are non trivial. I really wanted to try and get rid of ts-node for my personal projects, because I found the time to start tests to slow. Additionally while using ts-node, I got no linting or live feedback for tests. I found that the code quality of my test suite suffered a bit without instant feedback.

I want to implement something like this setup at work as well. However we use a relatively (overcomplicated) setup with gulp AND webpack, so I'll have to see how that will work out. I also have to convince my coworkers of course.

BTW: This setup is really awesome with typescripts new `--incremental` flag. Tests start incredibly quick if you dont manually purge the transpiled js files everytime.

**Pull request merged**
